# Generated by Django 2.2.4 on 2020-03-26 06:16

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orderdetails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='order',
            field=jsonfield.fields.JSONField(default=0),
            preserve_default=False,
        ),
    ]
