# Generated by Django 2.2.4 on 2020-03-24 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userdetails', '0003_auto_20200321_2014'),
        ('itemdetails', '0003_auto_20200322_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=5)),
                ('itemid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itemdetails.itemdetail')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdetails.UserDetails')),
            ],
        ),
    ]
