# Generated by Django 2.2.4 on 2020-03-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartdetail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdetail',
            name='itemid',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='cartdetail',
            name='userid',
            field=models.CharField(max_length=10),
        ),
    ]
