# Generated by Django 2.2.4 on 2020-03-25 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartdetail', '0002_auto_20200324_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdetail',
            name='itemid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itemdetails.itemdetail'),
        ),
    ]
