# Generated by Django 2.2.4 on 2020-03-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartdetail', '0003_auto_20200325_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartdetail',
            name='itemid',
        ),
        migrations.AddField(
            model_name='cartdetail',
            name='item_name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartdetail',
            name='item_price',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
