# Generated by Django 2.2.4 on 2020-03-25 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartdetail', '0004_auto_20200325_1233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartdetail',
            old_name='userid',
            new_name='emailid',
        ),
    ]
