# Generated by Django 2.2.4 on 2020-03-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartdetail', '0005_auto_20200325_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdetail',
            name='emailid',
            field=models.CharField(max_length=50),
        ),
    ]
