# Generated by Django 2.2.4 on 2020-03-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartdetail', '0006_auto_20200325_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdetail',
            name='price_per_item',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
