# Generated by Django 2.2.4 on 2020-03-25 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartdetail', '0007_cartdetail_price_per_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartdetail',
            name='price_per_item',
        ),
    ]
