# Generated by Django 3.0.4 on 2020-03-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemdetails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdetail',
            name='price',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='itemdetail',
            name='quantity',
            field=models.CharField(max_length=32),
        ),
    ]
