# Generated by Django 3.0.4 on 2020-03-22 17:20

from django.db import migrations, models
import itemdetails.models


class Migration(migrations.Migration):

    dependencies = [
        ('itemdetails', '0002_auto_20200322_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdetail',
            name='image',
            field=models.ImageField(upload_to=itemdetails.models.upload_path),
        ),
    ]
