# Generated by Django 2.2.4 on 2020-04-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemdetails', '0004_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdetail',
            name='image',
            field=models.CharField(max_length=100),
        ),
    ]
