# Generated by Django 2.2.11 on 2020-03-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='id',
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='user_email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
