# Generated by Django 2.2.11 on 2020-03-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0002_auto_20200321_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='user_email',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
