# Generated by Django 2.2.4 on 2020-03-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admindetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32)),
                ('phoneNo', models.BigIntegerField(default=0)),
                ('email', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=15)),
            ],
        ),
    ]
