# Generated by Django 2.2.4 on 2020-03-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admindetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('phoneNo', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
    ]
