# Generated by Django 3.0.4 on 2020-03-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindetails', '0002_admindetail_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admindetail',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='admindetail',
            name='phoneNo',
            field=models.IntegerField(max_length=15),
        ),
    ]
