# Generated by Django 2.2.4 on 2020-03-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindetails', '0002_admindetail_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='admindetail',
            name='message',
            field=models.CharField(default='', max_length=50),
        ),
    ]
