# Generated by Django 2.2.4 on 2020-03-20 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admindetails', '0003_admindetail_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admindetail',
            name='message',
        ),
    ]
