# Generated by Django 2.2.4 on 2020-03-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindetails', '0003_auto_20200321_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admindetail',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='admindetail',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='admindetail',
            name='password',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='admindetail',
            name='phoneNo',
            field=models.BigIntegerField(),
        ),
    ]
