# Generated by Django 2.2.4 on 2020-03-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindetails', '0005_auto_20200321_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admindetail',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='admindetail',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='admindetail',
            name='password',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='admindetail',
            name='phoneNo',
            field=models.CharField(max_length=15),
        ),
    ]
